// GENERATED CODE! DO NOT MODIFY BY HAND!
// Generated by scripts/generate-codex-manifest.mjs

export type OfficialConfigFieldSchema = {
  description: string | null;
  types: string[];
  enumValues: string[];
  hasObjectShape: boolean;
  hasArrayShape: boolean;
  unstable: boolean;
  deprecated: boolean;
};

export const SUPPLEMENTAL_REQUEST_METHODS = {
  "collaborationMode/list": "Official docs currently expose collaboration mode types but omit the list request in generated ClientRequest schema."
} as const;

export const OFFICIAL_REQUEST_METHODS = [
  "initialize",
  "thread/start",
  "thread/resume",
  "thread/fork",
  "thread/archive",
  "thread/unsubscribe",
  "thread/name/set",
  "thread/metadata/update",
  "thread/unarchive",
  "thread/compact/start",
  "thread/shellCommand",
  "thread/approveGuardianDeniedAction",
  "thread/rollback",
  "thread/list",
  "thread/loaded/list",
  "thread/read",
  "thread/inject_items",
  "skills/list",
  "hooks/list",
  "marketplace/add",
  "marketplace/remove",
  "marketplace/upgrade",
  "plugin/list",
  "plugin/read",
  "plugin/skill/read",
  "plugin/share/save",
  "plugin/share/updateTargets",
  "plugin/share/list",
  "plugin/share/delete",
  "app/list",
  "fs/readFile",
  "fs/writeFile",
  "fs/createDirectory",
  "fs/getMetadata",
  "fs/readDirectory",
  "fs/remove",
  "fs/copy",
  "fs/watch",
  "fs/unwatch",
  "skills/config/write",
  "plugin/install",
  "plugin/uninstall",
  "turn/start",
  "turn/steer",
  "turn/interrupt",
  "review/start",
  "model/list",
  "modelProvider/capabilities/read",
  "experimentalFeature/list",
  "experimentalFeature/enablement/set",
  "mcpServer/oauth/login",
  "config/mcpServer/reload",
  "mcpServerStatus/list",
  "mcpServer/resource/read",
  "mcpServer/tool/call",
  "windowsSandbox/setupStart",
  "windowsSandbox/readiness",
  "account/login/start",
  "account/login/cancel",
  "account/logout",
  "account/rateLimits/read",
  "account/sendAddCreditsNudgeEmail",
  "feedback/upload",
  "command/exec",
  "command/exec/write",
  "command/exec/terminate",
  "command/exec/resize",
  "config/read",
  "externalAgentConfig/detect",
  "externalAgentConfig/import",
  "config/value/write",
  "config/batchWrite",
  "configRequirements/read",
  "account/read",
  "getConversationSummary",
  "gitDiffToRemote",
  "getAuthStatus",
  "fuzzyFileSearch",
  "collaborationMode/list"
] as const;

export const OFFICIAL_NOTIFICATION_METHODS = [
  "error",
  "thread/started",
  "thread/status/changed",
  "thread/archived",
  "thread/unarchived",
  "thread/closed",
  "skills/changed",
  "thread/name/updated",
  "thread/goal/updated",
  "thread/goal/cleared",
  "thread/tokenUsage/updated",
  "turn/started",
  "hook/started",
  "turn/completed",
  "hook/completed",
  "turn/diff/updated",
  "turn/plan/updated",
  "item/started",
  "item/autoApprovalReview/started",
  "item/autoApprovalReview/completed",
  "item/completed",
  "rawResponseItem/completed",
  "item/agentMessage/delta",
  "item/plan/delta",
  "command/exec/outputDelta",
  "process/outputDelta",
  "process/exited",
  "item/commandExecution/outputDelta",
  "item/commandExecution/terminalInteraction",
  "item/fileChange/outputDelta",
  "item/fileChange/patchUpdated",
  "serverRequest/resolved",
  "item/mcpToolCall/progress",
  "mcpServer/oauthLogin/completed",
  "mcpServer/startupStatus/updated",
  "account/updated",
  "account/rateLimits/updated",
  "app/list/updated",
  "remoteControl/status/changed",
  "externalAgentConfig/import/completed",
  "fs/changed",
  "item/reasoning/summaryTextDelta",
  "item/reasoning/summaryPartAdded",
  "item/reasoning/textDelta",
  "thread/compacted",
  "model/rerouted",
  "model/verification",
  "warning",
  "guardianWarning",
  "deprecationNotice",
  "configWarning",
  "fuzzyFileSearch/sessionUpdated",
  "fuzzyFileSearch/sessionCompleted",
  "thread/realtime/started",
  "thread/realtime/itemAdded",
  "thread/realtime/transcript/delta",
  "thread/realtime/transcript/done",
  "thread/realtime/outputAudio/delta",
  "thread/realtime/sdp",
  "thread/realtime/error",
  "thread/realtime/closed",
  "windows/worldWritableWarning",
  "windowsSandbox/setupCompleted",
  "account/login/completed"
] as const;

export const OFFICIAL_SERVER_REQUEST_METHODS = [
  "item/commandExecution/requestApproval",
  "item/fileChange/requestApproval",
  "item/tool/requestUserInput",
  "mcpServer/elicitation/request",
  "item/permissions/requestApproval",
  "item/tool/call",
  "account/chatgptAuthTokens/refresh",
  "applyPatchApproval",
  "execCommandApproval"
] as const;

export const OFFICIAL_CONFIG_FIELD_SCHEMAS = {
  "analytics": {
    "description": null,
    "types": [
      "object",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": true,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "analytics.enabled": {
    "description": null,
    "types": [
      "boolean",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "approval_policy": {
    "description": null,
    "types": [
      "string",
      "object",
      "null"
    ],
    "enumValues": [
      "untrusted",
      "on-failure",
      "on-request",
      "never"
    ],
    "hasObjectShape": true,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "approvals_reviewer": {
    "description": "[UNSTABLE] Optional default for where approval requests are routed for review.",
    "types": [
      "string",
      "null"
    ],
    "enumValues": [
      "user",
      "auto_review",
      "guardian_subagent"
    ],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": true,
    "deprecated": false
  },
  "compact_prompt": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "developer_instructions": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "forced_chatgpt_workspace_id": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "forced_login_method": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [
      "chatgpt",
      "api"
    ],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "instructions": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "model": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "model_auto_compact_token_limit": {
    "description": null,
    "types": [
      "integer",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "model_context_window": {
    "description": null,
    "types": [
      "integer",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "model_provider": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "model_reasoning_effort": {
    "description": "See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#get-started-with-reasoning",
    "types": [
      "string",
      "null"
    ],
    "enumValues": [
      "none",
      "minimal",
      "low",
      "medium",
      "high",
      "xhigh"
    ],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "model_reasoning_summary": {
    "description": "Option to disable reasoning summaries.",
    "types": [
      "string",
      "null"
    ],
    "enumValues": [
      "auto",
      "concise",
      "detailed",
      "none"
    ],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "model_verbosity": {
    "description": "Controls output length/detail on GPT-5 models via the Responses API. Serialized with lowercase values to match the OpenAI API.",
    "types": [
      "string",
      "null"
    ],
    "enumValues": [
      "low",
      "medium",
      "high"
    ],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "profile": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "profiles": {
    "description": null,
    "types": [
      "object"
    ],
    "enumValues": [],
    "hasObjectShape": true,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "review_model": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "sandbox_mode": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [
      "read-only",
      "workspace-write",
      "danger-full-access"
    ],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "sandbox_workspace_write": {
    "description": null,
    "types": [
      "object",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": true,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "sandbox_workspace_write.exclude_slash_tmp": {
    "description": null,
    "types": [
      "boolean"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "sandbox_workspace_write.exclude_tmpdir_env_var": {
    "description": null,
    "types": [
      "boolean"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "sandbox_workspace_write.network_access": {
    "description": null,
    "types": [
      "boolean"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "sandbox_workspace_write.writable_roots": {
    "description": null,
    "types": [
      "array"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": true,
    "unstable": false,
    "deprecated": false
  },
  "service_tier": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "tools": {
    "description": null,
    "types": [
      "object",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": true,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "tools.view_image": {
    "description": null,
    "types": [
      "boolean",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "tools.web_search": {
    "description": null,
    "types": [
      "object",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": true,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "tools.web_search.allowed_domains": {
    "description": null,
    "types": [
      "array",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": true,
    "unstable": false,
    "deprecated": false
  },
  "tools.web_search.context_size": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [
      "low",
      "medium",
      "high"
    ],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "tools.web_search.location": {
    "description": null,
    "types": [
      "object",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": true,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "tools.web_search.location.city": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "tools.web_search.location.country": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "tools.web_search.location.region": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "tools.web_search.location.timezone": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  },
  "web_search": {
    "description": null,
    "types": [
      "string",
      "null"
    ],
    "enumValues": [
      "disabled",
      "cached",
      "live"
    ],
    "hasObjectShape": false,
    "hasArrayShape": false,
    "unstable": false,
    "deprecated": false
  }
} as const satisfies Record<string, OfficialConfigFieldSchema>;
